// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sological.Sms.Service.Data;

#nullable disable

namespace Sological.Sms.Service.Migrations
{
    [DbContext(typeof(SmsDbContext))]
    [Migration("20260727020546_S2SendLane")]
    partial class S2SendLane
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sological.Sms.Core.Entities.AllowedOriginator", b =>
                {
                    b.Property<string>("Originator")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("originator");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.HasKey("Originator")
                        .HasName("pk_allowed_originators");

                    b.ToTable("allowed_originators", (string)null);
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.BillingLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_id");

                    b.Property<string>("RefType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("ref_type");

                    b.Property<short>("Units")
                        .HasColumnType("smallint")
                        .HasColumnName("units");

                    b.HasKey("Id")
                        .HasName("pk_billing_ledger");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_billing_ledger_channel_id");

                    b.HasIndex("CustomerId", "OccurredAt")
                        .HasDatabaseName("ix_billing_ledger_customer_id_occurred_at");

                    b.ToTable("billing_ledger", (string)null);
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.Channel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiKey1Hash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("api_key_1_hash");

                    b.Property<string>("ApiKey2Hash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("api_key_2_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<int>("DuplicateWindowSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3600)
                        .HasColumnName("duplicate_window_seconds");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Originator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("originator");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Upstream")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("upstream");

                    b.Property<string>("WebhookSecretName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("webhook_secret_name");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_channels_customer_id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_key");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_code");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.DeliveryEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Dictionary<string, string>>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("RawDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("raw_description");

                    b.Property<string>("RawResult")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("raw_result");

                    b.Property<string>("RawStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("raw_status");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Id")
                        .HasName("pk_delivery_events");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_delivery_events_message_id");

                    b.ToTable("delivery_events", (string)null);
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.InboundMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean")
                        .HasColumnName("complete");

                    b.Property<DateTimeOffset?>("DeliveredToCustomerAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_to_customer_at");

                    b.Property<string>("FromNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_number");

                    b.Property<Dictionary<string, string>>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("reply_to_message_id");

                    b.Property<string>("ToNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_number");

                    b.Property<string>("UpstreamId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("upstream_id");

                    b.HasKey("Id")
                        .HasName("pk_inbound_messages");

                    b.HasIndex("ReplyToMessageId")
                        .HasDatabaseName("ix_inbound_messages_reply_to_message_id");

                    b.HasIndex("ChannelId", "ReceivedAt")
                        .HasDatabaseName("ix_inbound_messages_channel_id_received_at");

                    b.ToTable("inbound_messages", (string)null);
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.InboundPart", b =>
                {
                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<string>("FromNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_number");

                    b.Property<string>("GroupRef")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("group_ref");

                    b.Property<short>("PartNo")
                        .HasColumnType("smallint")
                        .HasColumnName("part_no");

                    b.Property<string>("BodyFragment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_fragment");

                    b.Property<short?>("Dcs")
                        .HasColumnType("smallint")
                        .HasColumnName("dcs");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<short>("TotalParts")
                        .HasColumnType("smallint")
                        .HasColumnName("total_parts");

                    b.HasKey("ChannelId", "FromNumber", "GroupRef", "PartNo")
                        .HasName("pk_inbound_parts");

                    b.ToTable("inbound_parts", (string)null);
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("claimed_by");

                    b.Property<string>("CustomerRef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_ref");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text")
                        .HasColumnName("error_detail");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("OriginatorUsed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("originator_used");

                    b.Property<short>("Parts")
                        .HasColumnType("smallint")
                        .HasColumnName("parts");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("ToNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_number");

                    b.Property<string>("Upstream")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("upstream");

                    b.Property<string>("UpstreamId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("upstream_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_messages_status_nonterminal")
                        .HasFilter("status IN ('queued', 'submitting', 'sent')");

                    b.HasIndex("ChannelId", "CustomerRef")
                        .HasDatabaseName("ix_messages_channel_id_customer_ref");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.WebhookOutboxEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_webhook_outbox");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_webhook_outbox_channel_id");

                    b.HasIndex("State", "NextAttemptAt")
                        .HasDatabaseName("ix_webhook_outbox_pending")
                        .HasFilter("state = 'pending'");

                    b.ToTable("webhook_outbox", (string)null);
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.BillingLedgerEntry", b =>
                {
                    b.HasOne("Sological.Sms.Core.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_billing_ledger_channels_channel_id");

                    b.HasOne("Sological.Sms.Core.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_billing_ledger_customers_customer_id");
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.Channel", b =>
                {
                    b.HasOne("Sological.Sms.Core.Entities.Customer", "Customer")
                        .WithMany("Channels")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_channels_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.DeliveryEvent", b =>
                {
                    b.HasOne("Sological.Sms.Core.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_delivery_events_messages_message_id");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.InboundMessage", b =>
                {
                    b.HasOne("Sological.Sms.Core.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inbound_messages_channels_channel_id");

                    b.HasOne("Sological.Sms.Core.Entities.Message", "ReplyToMessage")
                        .WithMany()
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inbound_messages_messages_reply_to_message_id");

                    b.Navigation("Channel");

                    b.Navigation("ReplyToMessage");
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.InboundPart", b =>
                {
                    b.HasOne("Sological.Sms.Core.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inbound_parts_channels_channel_id");
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.Message", b =>
                {
                    b.HasOne("Sological.Sms.Core.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_channels_channel_id");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.WebhookOutboxEntry", b =>
                {
                    b.HasOne("Sological.Sms.Core.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_outbox_channels_channel_id");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Sological.Sms.Core.Entities.Customer", b =>
                {
                    b.Navigation("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
